### ISSUE TITLE
tensorflow dependency issue

### ISSUE THREAD

**Issue by snkr-git** [lukeharwood11/ai-racecar-simulator#38]
got below error while trying to run example.py
    from keras.optimizer_v2.adam import Adam
ModuleNotFoundError: No module named 'keras.optimizer_v2'

installed keras version
Name: keras
Version: 2.10.0
Summary: Deep learning for humans.
Home-page: https://keras.io/
Author: Keras team
Author-email: keras-users@googlegroups.com
License: Apache 2.0
Location: /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages
Requires: 
Required-by: tensorflow

**Comment by lukeharwood11** [comment]
This project was built using keras v 2.7.0.
Merge to main uses the updated [tf.keras.optimizers.Adam](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam)

**Comment by lukeharwood11** [comment]
Please reopen if the issue still exists
